#Taller importación y extracción de datos
###Juan Esteban Barrantes
###Juan Camilo Ordoñez
###Daniel Alejandro Caicedo

####Librerias requeridas

In [ ]:
!pip install xlrd openpyxl
!pip install pandas
!pip install wbdata

Requirement already satisfied: xlrd in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: wbdata in /usr/local/lib/python3.12/dist-packages (1.1.0)
Requirement already satisfied: appdirs<2,>=1.4 in /usr/local/lib/python3.12/dist-packages (from wbdata) (1.4.4)
Requirement already satisfied: backoff<3,>=2.2.1 in /usr/local/lib/python3.12/dist-packages (from wbdata) (2.2.1)
Requirement already satisfied: cachetools<6,>=5.3.2 in /usr/local/lib/python3.12/dist-packages (from wbdata) (5.5.2)
Requirement already satisfied: dateparser<2,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from wbdata) (1.3.0)
Requirement already satisfied: decorator<6,>=5.1.1 in /usr/local/lib/python3.12/dist-packages (from wbdata) (5.2.1)
Requirement already satisfied: requests<3,>=2.0 in /usr/local/lib/python3.12/dist-packages (from wbdata) (2.32.4)
Requirement already satisfied: shelved-cache<0.4,>=0.3.1 in /usr/local/lib/python3.12/dist-packages (from wbdata) (0.3.1)
Requirement already satisfied: tabulate<1,>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from wbdata) (0.9.0)
Requirement already satisfied: python-dateutil>=2.7.0 in /usr/local/lib/python3.12/dist-packages (from dateparser<2,>=1.2.0->wbdata) (2.9.0.post0)
Requirement already satisfied: pytz>=2024.2 in /usr/local/lib/python3.12/dist-packages (from dateparser<2,>=1.2.0->wbdata) (2025.2)
Requirement already satisfied: regex>=2024.9.11 in /usr/local/lib/python3.12/dist-packages (from dateparser<2,>=1.2.0->wbdata) (2025.11.3)
Requirement already satisfied: tzlocal>=0.2 in /usr/local/lib/python3.12/dist-packages (from dateparser<2,>=1.2.0->wbdata) (5.3.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0->wbdata) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0->wbdata) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0->wbdata) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0->wbdata) (2026.2.25)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7.0->dateparser<2,>=1.2.0->wbdata) (1.17.0)

In [ ]:
import pandas as pd
import numpy as np
import wbdata
import datetime
import os
import requests

##Primer punto

In [ ]:
from google.colab import drive, files
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
path= '/content/drive/MyDrive/Dataset'

In [ ]:
os.chdir(path)

In [ ]:
df_mun_drive = pd.read_csv('/content/drive/MyDrive/Dataset/dataset_2026-03-05T13_12_12.035043298Z_DEFAULT_INTEGRATION_IMF.RES_WEO_9.0.0.csv', sep=",", decimal='.', encoding ='utf-8', converters={'Cod. Municipio':str})
df_mun_drive.head()

/tmp/ipykernel_722/3434495009.py:1: DtypeWarning: Columns (9,14,15,17,51,53,59) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mun_drive = pd.read_csv('/content/drive/MyDrive/Dataset/dataset_2026-03-05T13_12_12.035043298Z_DEFAULT_INTEGRATION_IMF.RES_WEO_9.0.0.csv', sep=",", decimal='.', encoding ='utf-8', converters={'Cod. Municipio':str})

,DATASET,SERIES_CODE,OBS_MEASURE,COUNTRY,INDICATOR,FREQUENCY,SCALE,DECIMALS_DISPLAYED,FUNCTIONAL_CAT,INT_ACC_ITEM,...,2021,2022,2023,2024,2025,2026,2027,2028,2029,2030
0,IMF.RES:WEO(9.0.0),LIE.LE.A,OBS_VALUE,"Liechtenstein, Principality of","Employed persons, Persons for countries / Inde...",Annual,Millions,Three,NaN,NaN,...,0.041,0.043,0.043,0.044,0.045,0.046,NaN,NaN,NaN,NaN
1,IMF.RES:WEO(9.0.0),CAN.LE.A,OBS_VALUE,Canada,"Employed persons, Persons for countries / Inde...",Annual,Millions,Three,NaN,NaN,...,18.973,19.748,20.341,20.723,21.009,21.080,NaN,NaN,NaN,NaN
2,IMF.RES:WEO(9.0.0),HND.NGDPPC.A,OBS_VALUE,Honduras,"Gross domestic product (GDP), Current prices, ...",Annual,Units,Three,NaN,NaN,...,66813.898,74749.009,80686.569,86300.122,95066.366,100495.041,106338.384,112815.742,119722.508,126957.554
3,IMF.RES:WEO(9.0.0),HND.LP.A,OBS_VALUE,Honduras,"Population, Persons for countries / Index for ...",Annual,Millions,Three,NaN,NaN,...,10.117,10.294,10.475,10.659,10.846,11.037,11.231,11.428,11.629,11.833
4,IMF.RES:WEO(9.0.0),BHS.LP.A,OBS_VALUE,"Bahamas, The","Population, Persons for countries / Index for ...",Annual,Millions,Three,NaN,NaN,...,0.394,0.399,0.404,0.408,0.413,0.417,0.421,0.425,0.429,0.434

In [ ]:
#primeras 5 filas
df_mun_drive.head()

,DATASET,SERIES_CODE,OBS_MEASURE,COUNTRY,INDICATOR,FREQUENCY,SCALE,DECIMALS_DISPLAYED,FUNCTIONAL_CAT,INT_ACC_ITEM,...,2021,2022,2023,2024,2025,2026,2027,2028,2029,2030
0,IMF.RES:WEO(9.0.0),LIE.LE.A,OBS_VALUE,"Liechtenstein, Principality of","Employed persons, Persons for countries / Inde...",Annual,Millions,Three,NaN,NaN,...,0.041,0.043,0.043,0.044,0.045,0.046,NaN,NaN,NaN,NaN
1,IMF.RES:WEO(9.0.0),CAN.LE.A,OBS_VALUE,Canada,"Employed persons, Persons for countries / Inde...",Annual,Millions,Three,NaN,NaN,...,18.973,19.748,20.341,20.723,21.009,21.080,NaN,NaN,NaN,NaN
2,IMF.RES:WEO(9.0.0),HND.NGDPPC.A,OBS_VALUE,Honduras,"Gross domestic product (GDP), Current prices, ...",Annual,Units,Three,NaN,NaN,...,66813.898,74749.009,80686.569,86300.122,95066.366,100495.041,106338.384,112815.742,119722.508,126957.554
3,IMF.RES:WEO(9.0.0),HND.LP.A,OBS_VALUE,Honduras,"Population, Persons for countries / Index for ...",Annual,Millions,Three,NaN,NaN,...,10.117,10.294,10.475,10.659,10.846,11.037,11.231,11.428,11.629,11.833
4,IMF.RES:WEO(9.0.0),BHS.LP.A,OBS_VALUE,"Bahamas, The","Population, Persons for countries / Index for ...",Annual,Millions,Three,NaN,NaN,...,0.394,0.399,0.404,0.408,0.413,0.417,0.421,0.425,0.429,0.434

In [ ]:
#1ultimas 10 filas
df_mun_drive.tail(10)

,DATASET,SERIES_CODE,OBS_MEASURE,COUNTRY,INDICATOR,FREQUENCY,SCALE,DECIMALS_DISPLAYED,FUNCTIONAL_CAT,INT_ACC_ITEM,...,2021,2022,2023,2024,2025,2026,2027,2028,2029,2030
8198,IMF.RES:WEO(9.0.0),TKM.TX_RPCH.A,OBS_VALUE,Turkmenistan,"Exports of goods and services, Volume, Free on...",Annual,Units,Three,NaN,NaN,...,19.192,-7.474,0.733,-6.036,-0.556,2.062,1.288,2.030,1.175,1.184
8199,IMF.RES:WEO(9.0.0),UZB.NGDP_D.A,OBS_VALUE,"Uzbekistan, Republic of","Gross domestic product (GDP), Price deflator, ...",Annual,Units,Three,NaN,NaN,...,113.693,130.136,148.100,167.860,189.814,207.942,225.316,241.202,257.549,274.883
8200,IMF.RES:WEO(9.0.0),MOZ.GGXWDG_NGDP.A,OBS_VALUE,"Mozambique, Republic of","Gross debt, General government, Percent of GDP",Annual,Units,Three,NaN,NaN,...,104.336,100.259,90.902,93.223,97.216,99.922,100.436,99.250,91.657,76.024
8201,IMF.RES:WEO(9.0.0),MOZ.GGXWDG.A,OBS_VALUE,"Mozambique, Republic of","Gross debt, General government, Domestic currency",Annual,Billions,Three,NaN,NaN,...,1104.332,1208.846,1214.963,1355.034,1554.484,1760.845,1951.509,2118.266,2254.308,2195.427
8202,IMF.RES:WEO(9.0.0),ZWE.GGXONLB_NGDP.A,OBS_VALUE,Zimbabwe,"Primary net lending (+) / net borrowing (-), G...",Annual,Units,Three,NaN,NaN,...,-1.768,-3.152,-3.603,-0.514,-0.118,0.384,0.586,0.544,0.502,0.461
8203,IMF.RES:WEO(9.0.0),ZWE.GGXONLB.A,OBS_VALUE,Zimbabwe,"Primary net lending (+) / net borrowing (-), G...",Annual,Billions,Three,NaN,NaN,...,-0.033,-0.233,-2.434,-4.229,-1.760,7.089,12.340,12.813,13.223,13.560
8204,IMF.RES:WEO(9.0.0),ZWE.GGR_NGDP.A,OBS_VALUE,Zimbabwe,"Revenue, General government, Percent of GDP",Annual,Units,Three,NaN,NaN,...,10.547,11.145,11.602,11.882,14.349,14.840,15.125,15.125,15.125,15.125
8205,IMF.RES:WEO(9.0.0),ZWE.GGR.A,OBS_VALUE,Zimbabwe,"Revenue, General government, Domestic currency",Annual,Billions,Three,NaN,NaN,...,0.196,0.823,7.838,97.781,214.207,274.004,318.736,356.308,398.202,445.318
8206,IMF.RES:WEO(9.0.0),ZWE.GGXCNL.A,OBS_VALUE,Zimbabwe,"Net lending (+) / net borrowing (-), General g...",Annual,Billions,Three,NaN,NaN,...,-0.042,-0.244,-2.637,-8.684,-11.163,-4.188,0.100,-0.752,-1.542,-2.683
8207,IMF.RES:WEO(9.0.0),ZWE.GGXCNL_NGDP.A,OBS_VALUE,Zimbabwe,"Net lending (+) / net borrowing (-), General g...",Annual,Units,Three,NaN,NaN,...,-2.239,-3.303,-3.904,-1.055,-0.748,-0.227,0.005,-0.032,-0.059,-0.091

In [ ]:
#3 filas aleatoreas
df_mun_drive.sample(3)

,DATASET,SERIES_CODE,OBS_MEASURE,COUNTRY,INDICATOR,FREQUENCY,SCALE,DECIMALS_DISPLAYED,FUNCTIONAL_CAT,INT_ACC_ITEM,...,2021,2022,2023,2024,2025,2026,2027,2028,2029,2030
6855,IMF.RES:WEO(9.0.0),KGZ.BCA.A,OBS_VALUE,Kyrgyz Republic,"Current account balance (credit less debit), U...",Annual,Billions,Three,NaN,Current account balance,...,-0.739,-5.144,-6.822,-4.424,-1.688,-1.657,-1.636,-1.699,-1.699,-1.733
2827,IMF.RES:WEO(9.0.0),SUR.PPPSH.A,OBS_VALUE,Suriname,"Gross domestic product (GDP), Purchasing power...",Annual,Units,Three,NaN,NaN,...,0.007,0.007,0.007,0.007,0.007,0.007,0.007,0.009,0.013,0.013
2608,IMF.RES:WEO(9.0.0),PRI.NGDP_R.A,OBS_VALUE,Puerto Rico,"Gross domestic product (GDP), Constant prices,...",Annual,Billions,Three,NaN,NaN,...,96.757,99.618,100.115,103.345,102.518,102.416,103.440,104.060,104.893,105.732

In [ ]:
#de la fila 2 a la 5 y columna 2
df_mun_drive.iloc[1:5, 1]

1        CAN.LE.A
2    HND.NGDPPC.A
3        HND.LP.A
4        BHS.LP.A
Name: SERIES_CODE, dtype: object

In [ ]:
#cuantas filas hay?
len(df_mun_drive)

8208

In [ ]:
#Numero de filas y columnas
df_mun_drive.shape

(8208, 116)

In [ ]:
#nombres de las columnas
df_mun_drive.columns

Index(['DATASET', 'SERIES_CODE', 'OBS_MEASURE', 'COUNTRY', 'INDICATOR',
       'FREQUENCY', 'SCALE', 'DECIMALS_DISPLAYED', 'FUNCTIONAL_CAT',
       'INT_ACC_ITEM',
       ...
       '2021', '2022', '2023', '2024', '2025', '2026', '2027', '2028', '2029',
       '2030'],
      dtype='object', length=116)

In [ ]:
#tipo de dato de cada columna
df_mun_drive.dtypes

DATASET         object
SERIES_CODE     object
OBS_MEASURE     object
COUNTRY         object
INDICATOR       object
                ...
2026           float64
2027           float64
2028           float64
2029           float64
2030           float64
Length: 116, dtype: object

In [ ]:
#informacion del dataset
df_mun_drive.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8208 entries, 0 to 8207
Columns: 116 entries, DATASET to 2030
dtypes: float64(59), object(57)
memory usage: 7.3+ MB

##Segundo punto

In [ ]:
indicador = {"FP.CPI.TOTL.ZG": "Inflación (%)"}
fecha_inicio = datetime.datetime(2010, 1, 1)
fecha_fin = datetime.datetime(2023, 1, 1)
paises = ["COL","ECU","BRA","CHL","MEX","PER"]
df_2 = wbdata.get_dataframe(indicador, country=paises, date=(fecha_inicio, fecha_fin))
df_2

              Inflación (%)
country date
Brazil  2023       4.593563
        2022       9.280106
        2021       8.301660
        2020       3.211768
        2019       3.732976
...                     ...
Peru    2014       3.411946
        2013       2.767897
        2012       3.611213
        2011       3.369311
        2010       1.528321

[84 rows x 1 columns]

In [ ]:
#primeras 5 filas
df_2.head()

              Inflación (%)
country date
Brazil  2023       4.593563
        2022       9.280106
        2021       8.301660
        2020       3.211768
        2019       3.732976

In [ ]:
#ultimas 10 filas
df_2.tail(10)

              Inflación (%)
country date
Peru    2019       2.252122
        2018       1.509154
        2017       2.994900
        2016       3.557177
        2015       3.398092
        2014       3.411946
        2013       2.767897
        2012       3.611213
        2011       3.369311
        2010       1.528321

In [ ]:
#3 filas aleatoreas
df_2.sample(3)

              Inflación (%)
country date
Chile   2023       7.581683
        2011       3.341217
Mexico  2012       4.111510

In [ ]:
#de la fila 2 a la 5 y la segunda columna
df_2.iloc[1:5, 0]

country  date
Brazil   2022    9.280106
         2021    8.301660
         2020    3.211768
         2019    3.732976
Name: Inflación (%), dtype: float64

In [ ]:
#cuantas filas hay?
len(df_2)

84

In [ ]:
#cuantas filas y columnas hay?
df_2.shape

(84, 1)

In [ ]:
#nombres de las columnas
df_2.columns

Index(['Inflación (%)'], dtype='object')

In [ ]:
#tipo de dato
df_2.dtypes

Inflación (%)    float64
dtype: object

In [ ]:
#informacion del dataset
df_2.info()

<class 'wbdata.client.DataFrame'>
MultiIndex: 84 entries, ('Brazil', '2023') to ('Peru', '2010')
Data columns (total 1 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Inflación (%)  84 non-null     float64
dtypes: float64(1)
memory usage: 1.8+ KB

##Tercer punto

In [ ]:
indicador = {"NY.GDP.MKTP.KD.ZG": "Crecimiento PIB (%)",
    "NY.GDP.PCAP.PP.KD": "PIB per cápita PPA",
    "FP.CPI.TOTL.ZG": "Inflación (%)",
    "SL.UEM.TOTL.ZS": "Desempleo (%)",
    "SP.POP.TOTL": "Población"}

fecha_inicio = datetime.datetime(2010, 1, 1)
fecha_fin = datetime.datetime(2023, 1, 1)

paises = ["DEU"]

df_3 = wbdata.get_dataframe(indicador, country=paises, date=(fecha_inicio, fecha_fin))

df_3

,Crecimiento PIB (%),PIB per cápita PPA,Inflación (%),Desempleo (%),Población
date,,,,,
2023,-0.869648,63039.371970,5.946437,3.071,83287273.0
2022,1.809258,63676.087822,6.872574,3.137,83177813.0
2021,3.910000,62530.765320,3.066667,3.594,83196078.0
2020,-4.131914,60203.289760,0.144878,3.881,83160871.0
2019,0.977735,62849.374187,1.445660,3.163,83092962.0
2018,1.135696,62381.347877,1.732169,3.384,82905782.0
2017,2.797907,61866.487221,1.509495,3.781,82657002.0
2016,2.222222,60407.971370,0.491747,4.104,82348669.0
2015,1.663006,59573.708954,0.514426,4.612,81686611.0
2014,2.180186,59108.697729,0.906794,4.979,80982500.0
2013,0.396996,58089.170854,1.504723,5.316,80645605.0
2012,0.463512,58017.585578,2.008489,5.372,80425823.0
2011,3.757969,57858.422260,2.075173,5.967,80274983.0
2010,4.134638,54738.708301,1.103810,7.043,81776930.0

In [ ]:
#primeras 5 filas
df_3.head()

,Crecimiento PIB (%),PIB per cápita PPA,Inflación (%),Desempleo (%),Población
date,,,,,
2023,-0.869648,63039.371970,5.946437,3.071,83287273.0
2022,1.809258,63676.087822,6.872574,3.137,83177813.0
2021,3.910000,62530.765320,3.066667,3.594,83196078.0
2020,-4.131914,60203.289760,0.144878,3.881,83160871.0
2019,0.977735,62849.374187,1.445660,3.163,83092962.0

In [ ]:
#ultimas 10 filas
df_3.tail(10)

,Crecimiento PIB (%),PIB per cápita PPA,Inflación (%),Desempleo (%),Población
date,,,,,
2019,0.977735,62849.374187,1.445660,3.163,83092962.0
2018,1.135696,62381.347877,1.732169,3.384,82905782.0
2017,2.797907,61866.487221,1.509495,3.781,82657002.0
2016,2.222222,60407.971370,0.491747,4.104,82348669.0
2015,1.663006,59573.708954,0.514426,4.612,81686611.0
2014,2.180186,59108.697729,0.906794,4.979,80982500.0
2013,0.396996,58089.170854,1.504723,5.316,80645605.0
2012,0.463512,58017.585578,2.008489,5.372,80425823.0
2011,3.757969,57858.422260,2.075173,5.967,80274983.0
2010,4.134638,54738.708301,1.103810,7.043,81776930.0

In [ ]:
#3 filas aleatoreas
df_3.sample(3)

,Crecimiento PIB (%),PIB per cápita PPA,Inflación (%),Desempleo (%),Población
date,,,,,
2022,1.809258,63676.087822,6.872574,3.137,83177813.0
2023,-0.869648,63039.371970,5.946437,3.071,83287273.0
2016,2.222222,60407.971370,0.491747,4.104,82348669.0

In [ ]:
#de la fila 2 a la 5 y la segunda columna
df_3.iloc[1:5, 1]

date
2022    63676.087822
2021    62530.765320
2020    60203.289760
2019    62849.374187
Name: PIB per cápita PPA, dtype: float64

In [ ]:
#cuantas filas hay?
len(df_3)

14

In [ ]:
#cuantas filas y columnas hay?
df_3.shape

(14, 5)

In [ ]:
#nombres de las columnas
df_3.columns

Index(['Crecimiento PIB (%)', 'PIB per cápita PPA', 'Inflación (%)',
       'Desempleo (%)', 'Población'],
      dtype='object')

In [ ]:
#tipo de dato de la columna
df_3.dtypes

Crecimiento PIB (%)    float64
PIB per cápita PPA     float64
Inflación (%)          float64
Desempleo (%)          float64
Población              float64
dtype: object

In [ ]:
#informacion del dataset
df_3.info()

<class 'wbdata.client.DataFrame'>
Index: 14 entries, 2023 to 2010
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Crecimiento PIB (%)  14 non-null     float64
 1   PIB per cápita PPA   14 non-null     float64
 2   Inflación (%)        14 non-null     float64
 3   Desempleo (%)        14 non-null     float64
 4   Población            14 non-null     float64
dtypes: float64(5)
memory usage: 1.2+ KB

##Cuarto punto

In [ ]:
#Delitos en colombia
url1 = "https://www.datos.gov.co/resource/gt2j-8ykr.csv"
df_col_1 = pd.read_csv(url1)
df_col_1.head()

,fecha_reporte_web,id_de_caso,fecha_de_notificaci_n,departamento,departamento_nom,ciudad_municipio,ciudad_municipio_nom,edad,unidad_medida,sexo,...,pais_viajo_1_cod,pais_viajo_1_nom,recuperado,fecha_inicio_sintomas,fecha_muerte,fecha_diagnostico,fecha_recuperado,tipo_recuperacion,per_etn_,nom_grupo_
0,2020-12-24 00:00:00,1556979,2020-12-22 00:00:00,76,VALLE,76001,CALI,67,1,F,...,NaN,NaN,Recuperado,2020-12-21 00:00:00,NaN,2020-12-23 00:00:00,2021-01-04 00:00:00,Tiempo,6,NaN
1,2020-12-24 00:00:00,1556980,2020-12-19 00:00:00,76,VALLE,76001,CALI,66,1,F,...,NaN,NaN,Recuperado,2020-12-07 00:00:00,NaN,2020-12-23 00:00:00,2020-12-25 00:00:00,Tiempo,6,NaN
2,2020-12-24 00:00:00,1556981,2020-12-19 00:00:00,76,VALLE,76001,CALI,68,1,F,...,NaN,NaN,Recuperado,2020-12-18 00:00:00,NaN,2020-12-22 00:00:00,2021-01-01 00:00:00,Tiempo,6,NaN
3,2020-12-24 00:00:00,1556982,2020-12-22 00:00:00,76,VALLE,76001,CALI,74,1,F,...,NaN,NaN,Fallecido,2020-12-17 00:00:00,2020-12-30 00:00:00,2020-12-23 00:00:00,NaN,NaN,6,NaN
4,2020-12-24 00:00:00,1556983,2020-12-22 00:00:00,76,VALLE,76001,CALI,65,1,F,...,NaN,NaN,Recuperado,2020-12-21 00:00:00,NaN,2020-12-23 00:00:00,2021-01-04 00:00:00,Tiempo,6,NaN

In [ ]:
#primeras 5 filas
df_col_1.head()

,fecha_reporte_web,id_de_caso,fecha_de_notificaci_n,departamento,departamento_nom,ciudad_municipio,ciudad_municipio_nom,edad,unidad_medida,sexo,...,pais_viajo_1_cod,pais_viajo_1_nom,recuperado,fecha_inicio_sintomas,fecha_muerte,fecha_diagnostico,fecha_recuperado,tipo_recuperacion,per_etn_,nom_grupo_
0,2020-12-24 00:00:00,1556979,2020-12-22 00:00:00,76,VALLE,76001,CALI,67,1,F,...,NaN,NaN,Recuperado,2020-12-21 00:00:00,NaN,2020-12-23 00:00:00,2021-01-04 00:00:00,Tiempo,6,NaN
1,2020-12-24 00:00:00,1556980,2020-12-19 00:00:00,76,VALLE,76001,CALI,66,1,F,...,NaN,NaN,Recuperado,2020-12-07 00:00:00,NaN,2020-12-23 00:00:00,2020-12-25 00:00:00,Tiempo,6,NaN
2,2020-12-24 00:00:00,1556981,2020-12-19 00:00:00,76,VALLE,76001,CALI,68,1,F,...,NaN,NaN,Recuperado,2020-12-18 00:00:00,NaN,2020-12-22 00:00:00,2021-01-01 00:00:00,Tiempo,6,NaN
3,2020-12-24 00:00:00,1556982,2020-12-22 00:00:00,76,VALLE,76001,CALI,74,1,F,...,NaN,NaN,Fallecido,2020-12-17 00:00:00,2020-12-30 00:00:00,2020-12-23 00:00:00,NaN,NaN,6,NaN
4,2020-12-24 00:00:00,1556983,2020-12-22 00:00:00,76,VALLE,76001,CALI,65,1,F,...,NaN,NaN,Recuperado,2020-12-21 00:00:00,NaN,2020-12-23 00:00:00,2021-01-04 00:00:00,Tiempo,6,NaN

In [ ]:
#ultimas 10 filas
df_col_1.tail(10)

,fecha_reporte_web,id_de_caso,fecha_de_notificaci_n,departamento,departamento_nom,ciudad_municipio,ciudad_municipio_nom,edad,unidad_medida,sexo,...,pais_viajo_1_cod,pais_viajo_1_nom,recuperado,fecha_inicio_sintomas,fecha_muerte,fecha_diagnostico,fecha_recuperado,tipo_recuperacion,per_etn_,nom_grupo_
990,2020-09-03 00:00:00,640268,2020-08-13 00:00:00,68,SANTANDER,68307,GIRON,23,1,M,...,NaN,NaN,Recuperado,2020-08-08 00:00:00,NaN,2020-08-24 00:00:00,2020-09-04 00:00:00,Tiempo,6,NaN
991,2020-09-03 00:00:00,640269,2020-08-14 00:00:00,68,SANTANDER,68081,BARRANCABERMEJA,45,1,F,...,NaN,NaN,Recuperado,2020-08-09 00:00:00,NaN,2020-08-25 00:00:00,2020-09-04 00:00:00,Tiempo,6,NaN
992,2020-09-03 00:00:00,640270,2020-08-11 00:00:00,5,ANTIOQUIA,5088,BELLO,34,1,M,...,NaN,NaN,Recuperado,2020-08-07 00:00:00,NaN,2020-08-22 00:00:00,2020-09-04 00:00:00,Tiempo,6,NaN
993,2020-09-03 00:00:00,640271,2020-08-12 00:00:00,68,SANTANDER,68276,FLORIDABLANCA,56,1,M,...,NaN,NaN,Recuperado,2020-08-07 00:00:00,NaN,2020-08-23 00:00:00,2020-09-04 00:00:00,Tiempo,6,NaN
994,2020-09-03 00:00:00,640272,2020-08-14 00:00:00,68,SANTANDER,68081,BARRANCABERMEJA,27,1,F,...,NaN,NaN,Recuperado,2020-08-09 00:00:00,NaN,2020-08-25 00:00:00,2020-09-04 00:00:00,PCR,6,NaN
995,2020-09-03 00:00:00,640273,2020-08-11 00:00:00,5,ANTIOQUIA,5088,BELLO,37,1,F,...,NaN,NaN,Recuperado,2020-08-07 00:00:00,NaN,2020-08-22 00:00:00,2020-09-04 00:00:00,Tiempo,6,NaN
996,2020-09-03 00:00:00,640274,2020-08-13 00:00:00,68,SANTANDER,68081,BARRANCABERMEJA,12,1,F,...,NaN,NaN,Recuperado,2020-08-08 00:00:00,NaN,2020-08-24 00:00:00,2020-09-04 00:00:00,Tiempo,6,NaN
997,2020-09-03 00:00:00,640275,2020-08-13 00:00:00,68,SANTANDER,68081,BARRANCABERMEJA,11,1,M,...,NaN,NaN,Recuperado,2020-08-08 00:00:00,NaN,2020-08-24 00:00:00,2020-09-04 00:00:00,Tiempo,6,NaN
998,2020-09-03 00:00:00,640276,2020-08-13 00:00:00,68,SANTANDER,68081,BARRANCABERMEJA,6,1,F,...,NaN,NaN,Recuperado,2020-08-08 00:00:00,NaN,2020-08-24 00:00:00,2020-09-04 00:00:00,Tiempo,6,NaN
999,2020-09-03 00:00:00,640277,2020-08-14 00:00:00,5,ANTIOQUIA,5088,BELLO,31,1,M,...,NaN,NaN,Recuperado,2020-08-10 00:00:00,NaN,2020-08-25 00:00:00,2020-09-04 00:00:00,Tiempo,6,NaN

In [ ]:
#3 filas aleatoreas
df_col_1.sample(3)

,fecha_reporte_web,id_de_caso,fecha_de_notificaci_n,departamento,departamento_nom,ciudad_municipio,ciudad_municipio_nom,edad,unidad_medida,sexo,...,pais_viajo_1_cod,pais_viajo_1_nom,recuperado,fecha_inicio_sintomas,fecha_muerte,fecha_diagnostico,fecha_recuperado,tipo_recuperacion,per_etn_,nom_grupo_
214,2021-01-14 00:00:00,1841915,2021-01-12 00:00:00,11,BOGOTA,11001,BOGOTA,53,1,M,...,NaN,NaN,Recuperado,2021-01-06 00:00:00,NaN,2021-01-12 00:00:00,2021-01-29 00:00:00,Tiempo,6,NaN
49,2020-12-24 00:00:00,1556943,2020-12-19 00:00:00,76,VALLE,76001,CALI,63,1,F,...,NaN,NaN,Fallecido,2020-12-14 00:00:00,2021-01-09 00:00:00,2020-12-22 00:00:00,NaN,NaN,6,NaN
337,2020-07-25 00:00:00,238797,2020-07-11 00:00:00,11,BOGOTA,11001,BOGOTA,50,1,M,...,NaN,NaN,Recuperado,2020-07-05 00:00:00,NaN,2020-07-24 00:00:00,2021-01-22 00:00:00,PCR,6,NaN

In [ ]:
#de la fila 2 a la 5 y la columna 2
df_col_1.iloc[1:5, 1]

1    1556980
2    1556981
3    1556982
4    1556983
Name: id_de_caso, dtype: int64

In [ ]:
#cuantas filas hay?
len(df_col_1)

1000

In [ ]:
#cuantas filas y columnas hay?
df_col_1.shape

(1000, 23)

In [ ]:
#nombres de las columnas
df_col_1.columns

Index(['fecha_reporte_web', 'id_de_caso', 'fecha_de_notificaci_n',
       'departamento', 'departamento_nom', 'ciudad_municipio',
       'ciudad_municipio_nom', 'edad', 'unidad_medida', 'sexo',
       'fuente_tipo_contagio', 'ubicacion', 'estado', 'pais_viajo_1_cod',
       'pais_viajo_1_nom', 'recuperado', 'fecha_inicio_sintomas',
       'fecha_muerte', 'fecha_diagnostico', 'fecha_recuperado',
       'tipo_recuperacion', 'per_etn_', 'nom_grupo_'],
      dtype='object')

In [ ]:
#tipo de dato de cada columna
df_col_1.dtypes

fecha_reporte_web         object
id_de_caso                 int64
fecha_de_notificaci_n     object
departamento               int64
departamento_nom          object
ciudad_municipio           int64
ciudad_municipio_nom      object
edad                       int64
unidad_medida              int64
sexo                      object
fuente_tipo_contagio      object
ubicacion                 object
estado                    object
pais_viajo_1_cod         float64
pais_viajo_1_nom         float64
recuperado                object
fecha_inicio_sintomas     object
fecha_muerte              object
fecha_diagnostico         object
fecha_recuperado          object
tipo_recuperacion         object
per_etn_                   int64
nom_grupo_                object
dtype: object

In [ ]:
#informacion del dataset
df_col_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   fecha_reporte_web      1000 non-null   object
 1   id_de_caso             1000 non-null   int64
 2   fecha_de_notificaci_n  1000 non-null   object
 3   departamento           1000 non-null   int64
 4   departamento_nom       1000 non-null   object
 5   ciudad_municipio       1000 non-null   int64
 6   ciudad_municipio_nom   1000 non-null   object
 7   edad                   1000 non-null   int64
 8   unidad_medida          1000 non-null   int64
 9   sexo                   1000 non-null   object
 10  fuente_tipo_contagio   1000 non-null   object
 11  ubicacion              994 non-null    object
 12  estado                 994 non-null    object
 13  pais_viajo_1_cod       0 non-null      float64
 14  pais_viajo_1_nom       0 non-null      float64
 15  recuperado             996 non-null    object
 16  fecha_inicio_sintomas  985 non-null    object
 17  fecha_muerte           41 non-null     object
 18  fecha_diagnostico      1000 non-null   object
 19  fecha_recuperado       961 non-null    object
 20  tipo_recuperacion      961 non-null    object
 21  per_etn_               1000 non-null   int64
 22  nom_grupo_             13 non-null     object
dtypes: float64(2), int64(6), object(15)
memory usage: 179.8+ KB

In [ ]:
#Accidentes de transito
url2 = "https://www.datos.gov.co/resource/72sg-cybi.csv"
df_col_2 = pd.read_csv(url2)
df_col_2.head()

,departamento,municipio,codigo_dane,armas_medios,fecha_hecho,genero,grupo_etario,descripci_n_conducta,cantidad
0,ANTIOQUIA,Santa Rosa de Osos,5686000,VEHICULO,29/01/2023,MASCULINO,ADULTOS,ARTÍCULO 120. LESIONES CULPOSAS ( EN ACCIDENTE...,2
1,CUNDINAMARCA,Bogotá D.C. (CT),11001000,VEHICULO,29/01/2023,MASCULINO,ADULTOS,ARTÍCULO 120. LESIONES CULPOSAS ( EN ACCIDENTE...,1
2,ANTIOQUIA,Campamento,5134000,VEHICULO,29/01/2023,MASCULINO,MENORES,ARTÍCULO 120. LESIONES CULPOSAS ( EN ACCIDENTE...,2
3,CUNDINAMARCA,Bogotá D.C. (CT),11001000,VEHICULO,25/01/2023,FEMENINO,ADULTOS,ARTÍCULO 120. LESIONES CULPOSAS ( EN ACCIDENTE...,1
4,BOYACÁ,Chiquinquirá,15176000,VEHICULO,29/01/2023,MASCULINO,ADULTOS,ARTÍCULO 120. LESIONES CULPOSAS ( EN ACCIDENTE...,4

In [ ]:
#primeras 5 filas
df_col_2.head()

,departamento,municipio,codigo_dane,armas_medios,fecha_hecho,genero,grupo_etario,descripci_n_conducta,cantidad
0,ANTIOQUIA,Santa Rosa de Osos,5686000,VEHICULO,29/01/2023,MASCULINO,ADULTOS,ARTÍCULO 120. LESIONES CULPOSAS ( EN ACCIDENTE...,2
1,CUNDINAMARCA,Bogotá D.C. (CT),11001000,VEHICULO,29/01/2023,MASCULINO,ADULTOS,ARTÍCULO 120. LESIONES CULPOSAS ( EN ACCIDENTE...,1
2,ANTIOQUIA,Campamento,5134000,VEHICULO,29/01/2023,MASCULINO,MENORES,ARTÍCULO 120. LESIONES CULPOSAS ( EN ACCIDENTE...,2
3,CUNDINAMARCA,Bogotá D.C. (CT),11001000,VEHICULO,25/01/2023,FEMENINO,ADULTOS,ARTÍCULO 120. LESIONES CULPOSAS ( EN ACCIDENTE...,1
4,BOYACÁ,Chiquinquirá,15176000,VEHICULO,29/01/2023,MASCULINO,ADULTOS,ARTÍCULO 120. LESIONES CULPOSAS ( EN ACCIDENTE...,4

In [ ]:
#ultimas 10 filas
df_col_2.tail(10)

,departamento,municipio,codigo_dane,armas_medios,fecha_hecho,genero,grupo_etario,descripci_n_conducta,cantidad
990,HUILA,Garzón,41298000,VEHICULO,02/04/2023,MASCULINO,ADULTOS,ARTÍCULO 120. LESIONES CULPOSAS ( EN ACCIDENTE...,1
991,VALLE,Tuluá,76834000,VEHICULO,02/04/2023,FEMENINO,ADULTOS,ARTÍCULO 120. LESIONES CULPOSAS ( EN ACCIDENTE...,1
992,HUILA,Garzón,41298000,VEHICULO,02/04/2023,FEMENINO,ADULTOS,ARTÍCULO 120. LESIONES CULPOSAS ( EN ACCIDENTE...,1
993,CAUCA,Caldono,19137000,VEHICULO,02/04/2023,FEMENINO,ADULTOS,ARTÍCULO 120. LESIONES CULPOSAS ( EN ACCIDENTE...,2
994,BOYACÁ,Sogamoso,15759000,VEHICULO,02/04/2023,FEMENINO,ADULTOS,ARTÍCULO 120. LESIONES CULPOSAS ( EN ACCIDENTE...,1
995,BOYACÁ,Paipa,15516000,VEHICULO,02/04/2023,MASCULINO,ADULTOS,ARTÍCULO 120. LESIONES CULPOSAS ( EN ACCIDENTE...,1
996,CUNDINAMARCA,Fusagasugá,25290000,VEHICULO,01/04/2023,FEMENINO,ADULTOS,ARTÍCULO 120. LESIONES CULPOSAS ( EN ACCIDENTE...,1
997,BOYACÁ,Ventaquemada,15861000,VEHICULO,31/03/2023,MASCULINO,ADULTOS,ARTÍCULO 120. LESIONES CULPOSAS ( EN ACCIDENTE...,1
998,BOYACÁ,Ventaquemada,15861000,VEHICULO,31/03/2023,FEMENINO,ADULTOS,ARTÍCULO 120. LESIONES CULPOSAS ( EN ACCIDENTE...,2
999,HUILA,Neiva (CT),41001000,VEHICULO,27/03/2023,FEMENINO,ADULTOS,ARTÍCULO 120. LESIONES CULPOSAS ( EN ACCIDENTE...,2

In [ ]:
#3 filas aleatoras
df_col_2.sample(3)

,departamento,municipio,codigo_dane,armas_medios,fecha_hecho,genero,grupo_etario,descripci_n_conducta,cantidad
911,CUNDINAMARCA,Bogotá D.C. (CT),11001000,VEHICULO,28/03/2023,MASCULINO,ADULTOS,ARTÍCULO 120. LESIONES CULPOSAS ( EN ACCIDENTE...,3
714,META,Villavicencio (CT),50001000,VEHICULO,14/03/2023,MASCULINO,ADULTOS,ARTÍCULO 120. LESIONES CULPOSAS ( EN ACCIDENTE...,5
966,META,Villavicencio (CT),50001000,VEHICULO,29/03/2023,FEMENINO,ADULTOS,ARTÍCULO 120. LESIONES CULPOSAS ( EN ACCIDENTE...,1

In [ ]:
# fila 2 a la 5 y la columna 2
df_col_2.iloc[1:5, 1]

1    Bogotá D.C. (CT)
2          Campamento
3    Bogotá D.C. (CT)
4        Chiquinquirá
Name: municipio, dtype: object

In [ ]:
#cuantas filas hay?
len(df_col_2)

1000

In [ ]:
#cuantas filas y columnas hay?
df_col_2.shape

(1000, 9)

In [ ]:
#cual es el nombre de las columnas
df_col_2.columns

Index(['departamento', 'municipio', 'codigo_dane', 'armas_medios',
       'fecha_hecho', 'genero', 'grupo_etario', 'descripci_n_conducta',
       'cantidad'],
      dtype='object')

In [ ]:
#tipo de dato de la columna
df_col_2.dtypes

departamento            object
municipio               object
codigo_dane              int64
armas_medios            object
fecha_hecho             object
genero                  object
grupo_etario            object
descripci_n_conducta    object
cantidad                 int64
dtype: object

In [ ]:
#informacion del dataset
df_col_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   departamento          1000 non-null   object
 1   municipio             1000 non-null   object
 2   codigo_dane           1000 non-null   int64
 3   armas_medios          1000 non-null   object
 4   fecha_hecho           1000 non-null   object
 5   genero                999 non-null    object
 6   grupo_etario          1000 non-null   object
 7   descripci_n_conducta  1000 non-null   object
 8   cantidad              1000 non-null   int64
dtypes: int64(2), object(7)
memory usage: 70.4+ KB

## Quinto punto

In [ ]:
url = "http://universities.hipolabs.com/search?country=Colombia"
data = requests.get(url).json()
df_uni = pd.DataFrame(data)
df_uni

,state-province,country,web_pages,domains,alpha_two_code,name
0,None,Colombia,[http://www.autonoma.edu.co/],[autonoma.edu.co],CO,Universidad Autónoma de Manizales
1,None,Colombia,[http://www.bellasartes.edu.co/],[bellasartes.edu.co],CO,Universidad Bellas Artes
2,None,Colombia,[http://www.bundenet.com/umusical/],[bundenet.com],CO,Conservatorio del Tolima
3,None,Colombia,[http://www.cesa.edu.co/],[cesa.edu.co],CO,Colegio de Estudios Superiores de Administraci...
4,None,Colombia,[http://www.ces.edu.co/],[ces.edu.co],CO,Universidad CES
...,...,...,...,...,...,...
98,None,Colombia,[http://www.utch.edu.co/],[utch.edu.co],CO,"Universidad Tecnológica del Choco ""Diego Luis ..."
99,None,Colombia,[http://www.ut.edu.co/],[ut.edu.co],CO,Universidad del Tolima
100,None,Colombia,[http://www.utp.edu.co/],[utp.edu.co],CO,Universidad Tecnológica de Pereira
101,None,Colombia,[https://universidadean.edu.co/],[universidadean.edu.co],CO,Universidad EAN
102,None,Colombia,[https://www.colmayor.edu.co/],[colmayor.edu.co],CO,Colegio Mayor de Antioquia

In [ ]:
#primeras 5 filas
df_uni.head()

,state-province,country,web_pages,domains,alpha_two_code,name
0,None,Colombia,[http://www.autonoma.edu.co/],[autonoma.edu.co],CO,Universidad Autónoma de Manizales
1,None,Colombia,[http://www.bellasartes.edu.co/],[bellasartes.edu.co],CO,Universidad Bellas Artes
2,None,Colombia,[http://www.bundenet.com/umusical/],[bundenet.com],CO,Conservatorio del Tolima
3,None,Colombia,[http://www.cesa.edu.co/],[cesa.edu.co],CO,Colegio de Estudios Superiores de Administraci...
4,None,Colombia,[http://www.ces.edu.co/],[ces.edu.co],CO,Universidad CES

In [ ]:
#ultimas 10 filas
df_uni.tail(10)

,state-province,country,web_pages,domains,alpha_two_code,name
93,None,Colombia,[http://www.usbmed.edu.co/],[usbmed.edu.co],CO,Universidad de San Buenaventura Medellin
94,None,Colombia,[http://www.usergioarboleda.edu.co/],[usergioarboleda.edu.co],CO,Universidad Sergio Arboleda
95,None,Colombia,[http://www.usta.edu.co/],[usta.edu.co],CO,Universidad Santo Tomás
96,None,Colombia,[http://www.usurcolombia.com/],[usurcolombia.com],CO,Universidad Surcolombiana
97,None,Colombia,[http://www.utadeo.edu.co/],[utadeo.edu.co],CO,"Universidad de Bogotá ""Jorge Tadeo Lozano"""
98,None,Colombia,[http://www.utch.edu.co/],[utch.edu.co],CO,"Universidad Tecnológica del Choco ""Diego Luis ..."
99,None,Colombia,[http://www.ut.edu.co/],[ut.edu.co],CO,Universidad del Tolima
100,None,Colombia,[http://www.utp.edu.co/],[utp.edu.co],CO,Universidad Tecnológica de Pereira
101,None,Colombia,[https://universidadean.edu.co/],[universidadean.edu.co],CO,Universidad EAN
102,None,Colombia,[https://www.colmayor.edu.co/],[colmayor.edu.co],CO,Colegio Mayor de Antioquia

In [ ]:
#3 filas aleatoreas
df_uni.sample(3)

,state-province,country,web_pages,domains,alpha_two_code,name
77,None,Colombia,[http://www.unincca.edu.co/],[unincca.edu.co],CO,Universidad INCCA de Colombia
90,None,Colombia,[http://www.urosario.edu.co/],[urosario.edu.co],CO,Universidad del Rosario
76,None,Colombia,[http://www.unimetro.edu.co/],[unimetro.edu.co],CO,Universidad Metropolitana

In [ ]:
# de la fila 2 a la 5 y la columna 2
df_uni.iloc[1:5, 1]

1    Colombia
2    Colombia
3    Colombia
4    Colombia
Name: country, dtype: object

In [ ]:
#cuantas filas hay?
len(df_uni)

103

In [ ]:
#cuantas filas y columnas hay?
df_uni.shape

(103, 6)

In [ ]:
#cual es el nombre de las columnas
df_uni.columns

Index(['state-province', 'country', 'web_pages', 'domains', 'alpha_two_code',
       'name'],
      dtype='object')

In [ ]:
#tipo de dato de las columnas
df_uni.dtypes

state-province    object
country           object
web_pages         object
domains           object
alpha_two_code    object
name              object
dtype: object

In [ ]:
#informacion del dataset
df_uni.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   state-province  0 non-null      object
 1   country         103 non-null    object
 2   web_pages       103 non-null    object
 3   domains         103 non-null    object
 4   alpha_two_code  103 non-null    object
 5   name            103 non-null    object
dtypes: object(6)
memory usage: 5.0+ KB