#**Taller de importacion y combinacion de datos**
###Intregrantes:
####- Manuela Vásquez Osorio
####- Juan Esteban Barrantes Riaño
####- Daniel Alejandro Caicedo Ballen

##1. Importe todas las librerías que vaya a utilizar.

In [ ]:
import pandas as pd
import numpy as np
import os
from google.colab import drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

##2. Mejorar la visualizacion de los datos

In [ ]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
pd.set_option('display.float_format', '{:.2f}'.format)

##3. Conéctese a su Google Drive y establezca la ruta de los datasets.

In [ ]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

##4. Cargue los datos en el notebook.

In [123]:
ruta = "/content/drive/MyDrive/GEIH 2025/"

##5.

In [124]:
meses = [
    "Julio",
    "Agosto",
    "Septiembre",
    "Octubre",
    "Noviembre",
    "Diciembre"
]

In [125]:
bases = []

for mes in meses:

    carpeta = ruta + mes + "/"

    caracteristicas = pd.read_csv(carpeta + "caracteristicas.csv", sep=";", encoding="latin-1", low_memory=False)
    hogar = pd.read_csv(carpeta + "hogar.csv", sep=";", encoding="latin-1", low_memory=False)
    fuerza = pd.read_csv(carpeta + "fuerza.csv", sep=";", encoding="latin-1", low_memory=False)
    ocupados = pd.read_csv(carpeta + "ocupados.csv", sep=";", encoding="latin-1", low_memory=False)

    fuerza = fuerza.drop(columns=["DPTO","PERIODO","MES","PER","CLASE","AREA","REGIS","FEX_C18","HOGAR"], errors="ignore")
    ocupados = ocupados.drop(columns=["DPTO","PERIODO","MES","PER","CLASE","AREA","REGIS","FEX_C18","HOGAR"], errors="ignore")

    base_mes = caracteristicas.merge(
        hogar,
        on=["DIRECTORIO","SECUENCIA_P"],
        how="left"
    )

    base_mes = base_mes.merge(
        fuerza,
        on=["DIRECTORIO","SECUENCIA_P","ORDEN"],
        how="left"
    )

    base_mes = base_mes.merge(
        ocupados,
        on=["DIRECTORIO","SECUENCIA_P","ORDEN"],
        how="left"
    )

    bases.append(base_mes)

In [126]:
geih_2025 = pd.concat(bases, ignore_index=True)

In [127]:
geih_2025.shape

(409127, 322)

In [128]:
columnas_limpias = [col for col in geih_2025.columns if not col.endswith('_x')]

geih_2025 = geih_2025[columnas_limpias]

In [129]:
geih_2025.head()

,DIRECTORIO,SECUENCIA_P,ORDEN,PT,P6016,P3271,P6040,P6030S1,P6030S3,P6050,P6083,P6083S1,P6081,P6081S1,P2057,P2059,P2061,P6080,P6080S1,P6080S1A1,P6070,P6071,P6071S1,P6090,P6100,P6110,P6120,P1906S1,P1906S2,P1906S3,P1906S4,P1906S5,P1906S6,P1906S7,P1906S8,P6160,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18,PERIODO_y,MES_y,PER_y,HOGAR_y,REGIS_y,AREA_y,CLASE_y,FEX_C18_y,DPTO_y,P4005,P4010,P4020,P4030S1,P4030S1A1,P4030S2,P4030S3,P4030S4,P4030S4A1,P4030S5,P70,P5000,P5010,P5020,P5030,P5040,P5050,P5070,P5080,P5090,P5090S1,P5100,P5110,P5130,P5140,P5222S1,P5222S2,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S8A1,P5222S9,P5222S10,P5222S11,P6008,FFT,PET,P6240,P6240S1,P6240S2,P6250,P6260,P6260S1,P6260S1A1,P6260S2,P6270,P6280,P3362S1,P3362S2,P3362S3,P3362S4,P3362S5,P3362S6,P3362S7,P3362S8,P3362S7A1,P6300,P6310,P6310S1,P6320,P6330,P6340,P6350,P6351,FT_y,P3044S2,P6440,P6450,P6460,P6460S1,P6400,P6410,P6422,P6420S2,P6424S1,P6424S2,P6424S3,P6424S5,P6426,P6430,P6430S1,P3045S1,P3045S2,P3045S3,P3046,P3363,P9440,P6500,P3364,P3364S1,P6510,P6510S1,P6510S2,P6590,P6590S1,P6600,P6600S1,P6610,P6610S1,P6620,P6620S1,P6585S1,P6585S1A1,P6585S1A2,P6585S2,P6585S2A1,P6585S2A2,P6585S3,P6585S3A1,P6585S3A2,P6585S4,P6585S4A1,P6585S4A2,P6545,P6545S1,P6545S2,P6580,P6580S1,P6580S2,P6630S1,P6630S1A1,P6630S2,P6630S2A1,P6630S3,P6630S3A1,P6630S4,P6630S4A1,P6630S6,P6630S6A1,P6640,P6640S1,P1800,P1800S1,P1801S1,P1801S2,P1801S3,P1802,P3047,P3048,P3049,P6765,P6765S1,P3051,P3052,P3053,P3365,P3365S1,P3054,P3054S1,P3055,P3055S1,P3056,P3057,P6760,P3058S1,P3058S2,P3058S3,P3058S4,P3058S5,P3059,P3061,P3062S1,P3062S2,P3062S3,P3062S4,P3062S5,P3062S6,P3062S7,P3062S8,P3062S9,P3063,P3063S1,P3064,P3064S1,P3065,P3066,P3067,P3067S1,P3067S2,P6775,P3068,P6750,P3073,P550,P6780,P6780S1,P1879,P1805,P6790,P6800,P6810,P6810S1,P6850,P6830,P6830S1,P3069,P6880,P6880S1,P6915,P6915S1,P6920,P6930,P6940,P6960,P6990,P9450,P7020,P760,P7026,P7028,P7028S1,P1880,P1880S1,P7040,P7045,P3071S3,P3072S2,P7050,P7070,P7075,P7077,P7090,P7100,P7110,P7120,P7130,P7140S1,P7140S2,P7140S3,P7140S4,P7140S5,P7140S6,P7140S7,P7140S8,P7140S9,P7140S9A1,P7150,P7160,P7170S1,P7170S5,P7170S6,P7180,P514,P515,P1881,P1881S1,P1882,P7240,P7240S1,OCI,INGLABO,RAMA2D_R4,RAMA4D_R4,OFICIO_C8
0,8283143,1,1,1,1,1,72,8.00,1952.00,1,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,2.00,1,3.00,NaN,NaN,4,4,4,3,3,4,4,4,2.00,2.00,NaN,1.00,0.00,NaN,NaN,NaN,2.00,1.00,1.00,20250731,7,2025,1,1,NaN,2,27.75,8,1,5,1,1,1.00,2,2,2,NaN,2,1,2,1,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,200000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,2,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,143.00,1.00,1.00,NaN,NaN,1.00,NaN,1.00,NaN,2.00,2.00,2.00,2.00,84.00,7.00,NaN,2.00,2.00,2.00,2.00,1.00,2.00,590000.00,2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,200000.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,40.00,NaN,NaN,40.00,NaN,NaN,2.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,0.00,3.00,4.00,NaN,3.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,3.00,NaN,10.00,3.00,NaN,1.00,790000.00,1.00,143.00,9212.00
1,8283143,1,2,1,2,2,34,8.00,1990.00,2,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,1.00,2,NaN,NaN,NaN,4,4,4,4,4,4,4,4,2.00,2.00,NaN,1.00,0.00,NaN,NaN,NaN,1.00,2.00,1.00,20250731,7,2025,1,1,NaN,2,27.75,8,1,5,1,1,1.00,2,2,2,NaN,2,1,2,1,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,200000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,2,1.00,1.00,4.00,NaN,NaN,2.00,2.00,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,8283145,1,1,1,1,1,45,6.00,1980.00,1,3,NaN,2,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,2.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,1.00,NaN,NaN,NaN,2.00,1.00,1.00,20250731,7,2025,1,1,NaN,2,59.11,8,1,2,1,1,1.00,2,2,2,NaN,2,1,3,2,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,100000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,4,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,141.00,1.00,1.00,NaN,NaN,1.00,NaN,1.00,NaN,2.00,2.00,2.00,2.00,48.00,1.00,NaN,2.00,2.00,2.00,2.00,1.00,2.00,1000000.00,2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,100000.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,70.00,NaN,NaN,70.00,NaN,NaN,2.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,1.00,36.00,7.00,NaN,7.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2.00,1.00,2.00,1.00,1.00,3.00,NaN,4.00,8.00,NaN,1.00,1100000.00,1.00,141.00,1311.00
3,8283145,1,2,1,2,2,50,2.00,1975.00,2,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,1.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,4.00,NaN,NaN,NaN,1.00,2.00,1.00,20250731,7,2025,1,1,NaN,2,59.11,8,1,2,1,1,1.00,2,2,2,NaN,2,1,3,2,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,100000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,4,1.00,1.00,4.00,NaN,NaN,2.00,2.00,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,9.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,8283145,1,3,1,3,1,19,6.00,2006.00,3,2,NaN,1,1.00,1,NaN,1,6,NaN,NaN,1.00,2.00,NaN,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,2.00,NaN,NaN,NaN,2.00,1.00,1.00,20250731,7,2025,1,1,NaN,2,59.11,8,1,2,1,1,1.00,2,2,2,NaN,2,1,3,2,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,100000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,4,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,141.00,1.00,1.00,NaN,NaN,1.00,NaN,1.00,NaN,2.00,2.00,2.00,2.00,48.00,7.00,NaN,2.00,2.00,2.00,2.00,1.00,2.00,720000.00,2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,100000.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,60.00,NaN,NaN,60.00,NaN,NaN,2.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,1.00,18.00,7.00,NaN,8.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2.00,1.00,2.00,1.00,1.00,3.00,NaN,3.00,3.00,NaN,1.00,820000.00,1.00,141.00,9212.00

In [130]:
geih_2025.columns

Index(['DIRECTORIO', 'SECUENCIA_P', 'ORDEN', 'PT', 'P6016', 'P3271', 'P6040',
       'P6030S1', 'P6030S3', 'P6050',
       ...
       'P1881', 'P1881S1', 'P1882', 'P7240', 'P7240S1', 'OCI', 'INGLABO',
       'RAMA2D_R4', 'RAMA4D_R4', 'OFICIO_C8'],
      dtype='object', length=312)

In [131]:
geih_2025.shape

(409127, 312)

In [132]:
print(geih_2025.duplicated().sum())
geih_2025[geih_2025.duplicated()]

0

Empty DataFrame
Columns: [DIRECTORIO, SECUENCIA_P, ORDEN, PT, P6016, P3271, P6040, P6030S1, P6030S3, P6050, P6083, P6083S1, P6081, P6081S1, P2057, P2059, P2061, P6080, P6080S1, P6080S1A1, P6070, P6071, P6071S1, P6090, P6100, P6110, P6120, P1906S1, P1906S2, P1906S3, P1906S4, P1906S5, P1906S6, P1906S7, P1906S8, P6160, P6170, P3041, P3042, P3042S1, P3042S2, P3043, P3043S1, P3038, P3039, POB_MAY18, PERIODO_y, MES_y, PER_y, HOGAR_y, REGIS_y, AREA_y, CLASE_y, FEX_C18_y, DPTO_y, P4005, P4010, P4020, P4030S1, P4030S1A1, P4030S2, P4030S3, P4030S4, P4030S4A1, P4030S5, P70, P5000, P5010, P5020, P5030, P5040, P5050, P5070, P5080, P5090, P5090S1, P5100, P5110, P5130, P5140, P5222S1, P5222S2, P5222S3, P5222S4, P5222S5, P5222S6, P5222S7, P5222S8, P5222S8A1, P5222S9, P5222S10, P5222S11, P6008, FFT, PET, P6240, P6240S1, P6240S2, P6250, P6260, ...]
Index: []

##7.

In [133]:
ciiu_maestro = pd.read_excel(ruta + "2025-01-14 Correlativa CIIU Rev4.xlsx", sheet_name='CIIU 2022')

In [134]:
print(ciiu_maestro.columns)

Index(['RAMA4D_R4', 'DESCRIPCION_CIIU'], dtype='object')

In [135]:
if 'DESCRIPCION_CIIU' in geih_2025.columns:
    geih_2025 = geih_2025.drop(columns=['DESCRIPCION_CIIU'])
if 'DESCRIPCION_CIIU_x' in geih_2025.columns:
    geih_2025 = geih_2025.drop(columns=['DESCRIPCION_CIIU_x'])

geih_2025 = pd.merge(geih_2025,
                       ciiu_maestro[['RAMA4D_R4', 'DESCRIPCION_CIIU']],
                       on='RAMA4D_R4',
                       how='left')
geih_2025

,DIRECTORIO,SECUENCIA_P,ORDEN,PT,P6016,P3271,P6040,P6030S1,P6030S3,P6050,P6083,P6083S1,P6081,P6081S1,P2057,P2059,P2061,P6080,P6080S1,P6080S1A1,P6070,P6071,P6071S1,P6090,P6100,P6110,P6120,P1906S1,P1906S2,P1906S3,P1906S4,P1906S5,P1906S6,P1906S7,P1906S8,P6160,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18,PERIODO_y,MES_y,PER_y,HOGAR_y,REGIS_y,AREA_y,CLASE_y,FEX_C18_y,DPTO_y,P4005,P4010,P4020,P4030S1,P4030S1A1,P4030S2,P4030S3,P4030S4,P4030S4A1,P4030S5,P70,P5000,P5010,P5020,P5030,P5040,P5050,P5070,P5080,P5090,P5090S1,P5100,P5110,P5130,P5140,P5222S1,P5222S2,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S8A1,P5222S9,P5222S10,P5222S11,P6008,FFT,PET,P6240,P6240S1,P6240S2,P6250,P6260,P6260S1,P6260S1A1,P6260S2,P6270,P6280,P3362S1,P3362S2,P3362S3,P3362S4,P3362S5,P3362S6,P3362S7,P3362S8,P3362S7A1,P6300,P6310,P6310S1,P6320,P6330,P6340,P6350,P6351,FT_y,P3044S2,P6440,P6450,P6460,P6460S1,P6400,P6410,P6422,P6420S2,P6424S1,P6424S2,P6424S3,P6424S5,P6426,P6430,P6430S1,P3045S1,P3045S2,P3045S3,P3046,P3363,P9440,P6500,P3364,P3364S1,P6510,P6510S1,P6510S2,P6590,P6590S1,P6600,P6600S1,P6610,P6610S1,P6620,P6620S1,P6585S1,P6585S1A1,P6585S1A2,P6585S2,P6585S2A1,P6585S2A2,P6585S3,P6585S3A1,P6585S3A2,P6585S4,P6585S4A1,P6585S4A2,P6545,P6545S1,P6545S2,P6580,P6580S1,P6580S2,P6630S1,P6630S1A1,P6630S2,P6630S2A1,P6630S3,P6630S3A1,P6630S4,P6630S4A1,P6630S6,P6630S6A1,P6640,P6640S1,P1800,P1800S1,P1801S1,P1801S2,P1801S3,P1802,P3047,P3048,P3049,P6765,P6765S1,P3051,P3052,P3053,P3365,P3365S1,P3054,P3054S1,P3055,P3055S1,P3056,P3057,P6760,P3058S1,P3058S2,P3058S3,P3058S4,P3058S5,P3059,P3061,P3062S1,P3062S2,P3062S3,P3062S4,P3062S5,P3062S6,P3062S7,P3062S8,P3062S9,P3063,P3063S1,P3064,P3064S1,P3065,P3066,P3067,P3067S1,P3067S2,P6775,P3068,P6750,P3073,P550,P6780,P6780S1,P1879,P1805,P6790,P6800,P6810,P6810S1,P6850,P6830,P6830S1,P3069,P6880,P6880S1,P6915,P6915S1,P6920,P6930,P6940,P6960,P6990,P9450,P7020,P760,P7026,P7028,P7028S1,P1880,P1880S1,P7040,P7045,P3071S3,P3072S2,P7050,P7070,P7075,P7077,P7090,P7100,P7110,P7120,P7130,P7140S1,P7140S2,P7140S3,P7140S4,P7140S5,P7140S6,P7140S7,P7140S8,P7140S9,P7140S9A1,P7150,P7160,P7170S1,P7170S5,P7170S6,P7180,P514,P515,P1881,P1881S1,P1882,P7240,P7240S1,OCI,INGLABO,RAMA2D_R4,RAMA4D_R4,OFICIO_C8,DESCRIPCION_CIIU
0,8283143,1,1,1,1,1,72,8.00,1952.00,1,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,2.00,1,3.00,NaN,NaN,4,4,4,3,3,4,4,4,2.00,2.00,NaN,1.00,0.00,NaN,NaN,NaN,2.00,1.00,1.00,20250731,7,2025,1,1,NaN,2,27.75,8,1,5,1,1,1.00,2,2,2,NaN,2,1,2,1,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,200000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,2,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,143.00,1.00,1.00,NaN,NaN,1.00,NaN,1.00,NaN,2.00,2.00,2.00,2.00,84.00,7.00,NaN,2.00,2.00,2.00,2.00,1.00,2.00,590000.00,2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,200000.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,40.00,NaN,NaN,40.00,NaN,NaN,2.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,0.00,3.00,4.00,NaN,3.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,3.00,NaN,10.00,3.00,NaN,1.00,790000.00,1.00,143.00,9212.00,Cría de ovejas y cabras
1,8283143,1,2,1,2,2,34,8.00,1990.00,2,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,1.00,2,NaN,NaN,NaN,4,4,4,4,4,4,4,4,2.00,2.00,NaN,1.00,0.00,NaN,NaN,NaN,1.00,2.00,1.00,20250731,7,2025,1,1,NaN,2,27.75,8,1,5,1,1,1.00,2,2,2,NaN,2,1,2,1,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,200000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,2,1.00,1.00,4.00,NaN,NaN,2.00,2.00,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,8283145,1,1,1,1,1,45,6.00,1980.00,1,3,NaN,2,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,2.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,1.00,NaN,NaN,NaN,2.00,1.00,1.00,20250731,7,2025,1,1,NaN,2,59.11,8,1,2,1,1,1.00,2,2,2,NaN,2,1,3,2,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,100000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,4,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,141.00,1.00,1.00,NaN,NaN,1.00,NaN,1.00,NaN,2.00,2.00,2.00,2.00,48.00,1.00,NaN,2.00,2.00,2.00,2.00,1.00,2.00,1000000.00,2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,100000.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,70.00,NaN,NaN,70.00,NaN,NaN,2.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,1.00,36.00,7.00,NaN,7.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2.00,1.00,2.00,1.00,1.00,3.00,NaN,4.00,8.00,NaN,1.00,1100000.00,1.00,141.00,1311.00,Cría de ganado bovino y bufalino
3,8283145,1,2,1,2,2,50,2.00,1975.00,2,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,1.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,4.00,NaN,NaN,NaN,1.00,2.00,1.00,20250731,7,2025,1,1,NaN,2,59.11,8,1,2,1,1,1.00,2,2,2,NaN,2,1,3,2,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,100000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,4,1.00,1.00,4.00,NaN,NaN,2.00,2.00,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,9.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,8283145,1,3,1,3,1,19,6.00,2006.00,3,2,NaN,1,1.00,1,NaN,1,6,NaN,NaN,1.00,2.00,NaN,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,2.00,NaN,NaN,NaN,2.00,1.00,1.00,20250731,7,2025,1,1,NaN,2,59.11,8,1,2,1,1,1.00,2,2,2,NaN,2,1,3,2,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,100000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,4,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,141.00,1.00,1.00,NaN,NaN,1.00,NaN,1.00,NaN,2.00,2.00,2.00,2.00,48.00,7.00,NaN,2.00,2.00,2.00,2.00,1.00,2.00,720000.00,2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,100000.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,60.00,NaN,NaN,60.00,NaN,NaN,2.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,1.00,18.00,7.00,NaN,8.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2.00,1.00,2.00,1.00,1.00,3.00,NaN,3.00,3.00,NaN,1.00,820000.00,1.00,141.00,9212.00,Cría de ganado bovino y bufalino
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
409122,8473907,1,1,1,1,2,61,6.00,1964.00,1,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,3.00,2.00,NaN,1,1.00,5.00,NaN,4,4,3,4,4,4,4,4,1.00,2.00,NaN,3.00,3.00,NaN,NaN,NaN,1.00,2.00,1.00,20251252,12,2025,1,1,NaN,2,378.31,73,1,1,4,1,2.00,2,2,2,NaN,1,1,4,1,2,1.00,4,1,1,4.00,4,NaN,NaN,NaN,600000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,1,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,9700.00,1.00,1.00,NaN,NaN,1.00,NaN,2.00,NaN,2.00,2.00,2.00,2.00,1.00,3.00,NaN,2.00,2.00,2.00,2.00,1.00,2.00,800000.00,2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,600000.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,48.00,NaN,NaN,48.00,NaN,NaN,1.00,1.00,NaN,3.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,72.00,0.00,4.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,14.00,NaN,NaN,3.00,NaN,1.00,1400000.00,97.00,9700.00,9111.00,Actividades de los hogares individuales como e...
409123,8473908,1,1,1,1,1,58,3.00,1967.00,1,3,NaN,3,NaN,2,2.00,2,6,NaN,NaN,3.00,1.00,2.00,1,2.00,1.00,120000.00,4,4,4,4,4,4,4,4,1.00,1.00,2.00,13.00,9.00,111.00,9.00,111.00,2.00,1.00,1.00,20251252,12,2025,1,1,54.00,1,534.55,54,2,1,4,1,2.00,1,1,1,3.00,1,1,4,3,1,1.00,1,1,1,3.00,1,NaN,NaN,300000000.00,700000.00,NaN,NaN,1.00,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,1.00,4,NaN,1.00,6.00,VACACIONES,NaN,2.00,1.00,3.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,8530.00,1.00,2.00,1.00,NaN,2.00,4.00,1.00,8413.00,1.00,1.00,1.00,1.00,60.00,2.00,NaN,2.00,1.00,2.00,1.00,5.00,2.00,3000000.00,2.00,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,1.00,1500000.00,1.00,3000000.00,1.00,1500000.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,30.00,2.00,NaN,0.00,3.00,NaN,10.00,7.00,NaN,1.00,NaN,1.00,3.00,1.00,20.00,1.00,1.00,1.00,0.00,48.00,4.00,NaN,8.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,8.00,NaN,30.00,2.00,NaN,1.00,3000000.00,85.00,8530.00,2330.00,Establecimientos que combinan diferentes nivel...
409124,8473908,1,2,1,2,2,51,3.00,1974.00,2,2,NaN,2,NaN,2,1.00,2,6,NaN,NaN,3.00,1.00,1.00,1,1.00,1.00,318240.00,4,4,4,4,4,4,4,4,1.00,2.00,NaN,12.00,4.00,413.00,9.00,413.00,1.00,2.00,1.00,20251252,12,2025,1,1,54.00,1,534.55,54,2,1,4,1,2.00,1,1,1,3.00,1,1,4,3,1,1.00,1,1,1,3.00,1,NaN,NaN,300000000.00,700000.00,NaN,NaN,1.00,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,1.00,4,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,8412.00,1.00,2.00,2.00,24.00,1.00,NaN,1.00,NaN,1.00,1.00,1.00,1.00,23.00,2.00,NaN,2.00,1.00,2.00,1.00,1.00,2.00,7956000.00,1.00,79600.00,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,1.00,3500000.00,1.00,7956000.00,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,44.00,NaN,NaN,44.00,NaN,NaN,10.00,7.00,NaN,1.00,NaN,1.00,2.00,1.00,10.00,1.00,1.00,1.00,4.00,48.00,4.00,NaN,1.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,2.00,NaN,60.00,2.00,NaN,1.00,7956000.00,84.00,8412.00,2411.00,Actividades ejecutivas de la administración pú...
409125,8473908,1,3,1,3,2,31,2.00,1994.00,3,1,2.00,1,1.00,2,2.00,2,6,NaN,NaN,6.00,NaN,NaN,1,1.00,3.00,178000.00,4,4,4,4,4,4,4,4,1.00,2.00,NaN,10.00,10.00,719.00,7.00,719.00,1.00,2.00,1.00,20251252,12,2025,1,1,54.00,1,534.55,54,2,1,4,1,2.00,1,1,1,3.00,1,1,4,3,1,1.00,1,1,1,3.00,1,NaN,NaN,300000000.00,700000.00,NaN,NaN,1.00,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,1.00,4,NaN,1.00,2.00,NaN,NaN,2.00,2.00,NaN,NaN,NaN,2.00,1.00,NaN,1.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
409126,8473908,1,4,1,4,2,26,2.00,1999.00,3,1,2.00,1,1.00,2,2.00,2,6,NaN,NaN,6.00,NaN,NaN,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,10.00,10.00,421.00,7.00,421.00,1.00,2.00,1.00,20251252,12,2025,1,1,54.00,1,534.55,54,2,1,4,1,2.00,1,1,1,3.00,1,1,4,3,1,1.00,1,1,1,3.00,1,NaN,NaN,300000000.00,700000.00,NaN,NaN,1.00,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,1.00,4,NaN,1.00,6.00,DESCANSANDO EN SU HOGAR,NaN,2.00,1.00,5.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,4791.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.00,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,3.00,1.00,1.00,1.00,6.00,NaN,NaN,700000.00,1.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,500000.00,1.00,NaN,1.00,NaN,1.00,2.00,10.00,10.00,1.00,NaN,0.00,5.00,NaN,1.00,1.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,0.00,6.00,4.00,NaN,3.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,44.00,2.00,2.00,1.00,1.00,1.00,1.00,1.00,2.00,2.00,2.00,2.00,2.00,NaN,1.00,1.00,1.00,2.00,1.00,2.00,2.00,1.00,14.00,NaN,NaN,2.00,NaN,1.00,500000.00,47.00,4791.00,5221.00,Comercio al por menor realizado a través de in...

In [136]:
geih_2025.shape

(409127, 313)

##8.

In [137]:
divipola_maestro = pd.read_excel(ruta + "2025-01-14 DIVIPOLA.xlsx", sheet_name='Departamentos', header=9)

In [138]:
print(divipola_maestro.columns)

Index(['Código', 'Nombre'], dtype='object')

In [139]:
geih_2025 = pd.merge(geih_2025,
                     divipola_maestro[['Código', 'Nombre']],
                     left_on='DPTO_y',
                     right_on='Código',
                     how='left')

geih_2025 = geih_2025.rename(columns={'Nombre': 'NOMBRE_DEPARTAMENTO'})
geih_2025

,DIRECTORIO,SECUENCIA_P,ORDEN,PT,P6016,P3271,P6040,P6030S1,P6030S3,P6050,P6083,P6083S1,P6081,P6081S1,P2057,P2059,P2061,P6080,P6080S1,P6080S1A1,P6070,P6071,P6071S1,P6090,P6100,P6110,P6120,P1906S1,P1906S2,P1906S3,P1906S4,P1906S5,P1906S6,P1906S7,P1906S8,P6160,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18,PERIODO_y,MES_y,PER_y,HOGAR_y,REGIS_y,AREA_y,CLASE_y,FEX_C18_y,DPTO_y,P4005,P4010,P4020,P4030S1,P4030S1A1,P4030S2,P4030S3,P4030S4,P4030S4A1,P4030S5,P70,P5000,P5010,P5020,P5030,P5040,P5050,P5070,P5080,P5090,P5090S1,P5100,P5110,P5130,P5140,P5222S1,P5222S2,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S8A1,P5222S9,P5222S10,P5222S11,P6008,FFT,PET,P6240,P6240S1,P6240S2,P6250,P6260,P6260S1,P6260S1A1,P6260S2,P6270,P6280,P3362S1,P3362S2,P3362S3,P3362S4,P3362S5,P3362S6,P3362S7,P3362S8,P3362S7A1,P6300,P6310,P6310S1,P6320,P6330,P6340,P6350,P6351,FT_y,P3044S2,P6440,P6450,P6460,P6460S1,P6400,P6410,P6422,P6420S2,P6424S1,P6424S2,P6424S3,P6424S5,P6426,P6430,P6430S1,P3045S1,P3045S2,P3045S3,P3046,P3363,P9440,P6500,P3364,P3364S1,P6510,P6510S1,P6510S2,P6590,P6590S1,P6600,P6600S1,P6610,P6610S1,P6620,P6620S1,P6585S1,P6585S1A1,P6585S1A2,P6585S2,P6585S2A1,P6585S2A2,P6585S3,P6585S3A1,P6585S3A2,P6585S4,P6585S4A1,P6585S4A2,P6545,P6545S1,P6545S2,P6580,P6580S1,P6580S2,P6630S1,P6630S1A1,P6630S2,P6630S2A1,P6630S3,P6630S3A1,P6630S4,P6630S4A1,P6630S6,P6630S6A1,P6640,P6640S1,P1800,P1800S1,P1801S1,P1801S2,P1801S3,P1802,P3047,P3048,P3049,P6765,P6765S1,P3051,P3052,P3053,P3365,P3365S1,P3054,P3054S1,P3055,P3055S1,P3056,P3057,P6760,P3058S1,P3058S2,P3058S3,P3058S4,P3058S5,P3059,P3061,P3062S1,P3062S2,P3062S3,P3062S4,P3062S5,P3062S6,P3062S7,P3062S8,P3062S9,P3063,P3063S1,P3064,P3064S1,P3065,P3066,P3067,P3067S1,P3067S2,P6775,P3068,P6750,P3073,P550,P6780,P6780S1,P1879,P1805,P6790,P6800,P6810,P6810S1,P6850,P6830,P6830S1,P3069,P6880,P6880S1,P6915,P6915S1,P6920,P6930,P6940,P6960,P6990,P9450,P7020,P760,P7026,P7028,P7028S1,P1880,P1880S1,P7040,P7045,P3071S3,P3072S2,P7050,P7070,P7075,P7077,P7090,P7100,P7110,P7120,P7130,P7140S1,P7140S2,P7140S3,P7140S4,P7140S5,P7140S6,P7140S7,P7140S8,P7140S9,P7140S9A1,P7150,P7160,P7170S1,P7170S5,P7170S6,P7180,P514,P515,P1881,P1881S1,P1882,P7240,P7240S1,OCI,INGLABO,RAMA2D_R4,RAMA4D_R4,OFICIO_C8,DESCRIPCION_CIIU,Código,NOMBRE_DEPARTAMENTO
0,8283143,1,1,1,1,1,72,8.00,1952.00,1,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,2.00,1,3.00,NaN,NaN,4,4,4,3,3,4,4,4,2.00,2.00,NaN,1.00,0.00,NaN,NaN,NaN,2.00,1.00,1.00,20250731,7,2025,1,1,NaN,2,27.75,8,1,5,1,1,1.00,2,2,2,NaN,2,1,2,1,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,200000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,2,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,143.00,1.00,1.00,NaN,NaN,1.00,NaN,1.00,NaN,2.00,2.00,2.00,2.00,84.00,7.00,NaN,2.00,2.00,2.00,2.00,1.00,2.00,590000.00,2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,200000.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,40.00,NaN,NaN,40.00,NaN,NaN,2.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,0.00,3.00,4.00,NaN,3.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,3.00,NaN,10.00,3.00,NaN,1.00,790000.00,1.00,143.00,9212.00,Cría de ovejas y cabras,NaN,NaN
1,8283143,1,2,1,2,2,34,8.00,1990.00,2,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,1.00,2,NaN,NaN,NaN,4,4,4,4,4,4,4,4,2.00,2.00,NaN,1.00,0.00,NaN,NaN,NaN,1.00,2.00,1.00,20250731,7,2025,1,1,NaN,2,27.75,8,1,5,1,1,1.00,2,2,2,NaN,2,1,2,1,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,200000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,2,1.00,1.00,4.00,NaN,NaN,2.00,2.00,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,8283145,1,1,1,1,1,45,6.00,1980.00,1,3,NaN,2,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,2.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,1.00,NaN,NaN,NaN,2.00,1.00,1.00,20250731,7,2025,1,1,NaN,2,59.11,8,1,2,1,1,1.00,2,2,2,NaN,2,1,3,2,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,100000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,4,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,141.00,1.00,1.00,NaN,NaN,1.00,NaN,1.00,NaN,2.00,2.00,2.00,2.00,48.00,1.00,NaN,2.00,2.00,2.00,2.00,1.00,2.00,1000000.00,2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,100000.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,70.00,NaN,NaN,70.00,NaN,NaN,2.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,1.00,36.00,7.00,NaN,7.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2.00,1.00,2.00,1.00,1.00,3.00,NaN,4.00,8.00,NaN,1.00,1100000.00,1.00,141.00,1311.00,Cría de ganado bovino y bufalino,NaN,NaN
3,8283145,1,2,1,2,2,50,2.00,1975.00,2,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,1.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,4.00,NaN,NaN,NaN,1.00,2.00,1.00,20250731,7,2025,1,1,NaN,2,59.11,8,1,2,1,1,1.00,2,2,2,NaN,2,1,3,2,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,100000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,4,1.00,1.00,4.00,NaN,NaN,2.00,2.00,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,9.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,8283145,1,3,1,3,1,19,6.00,2006.00,3,2,NaN,1,1.00,1,NaN,1,6,NaN,NaN,1.00,2.00,NaN,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,2.00,NaN,NaN,NaN,2.00,1.00,1.00,20250731,7,2025,1,1,NaN,2,59.11,8,1,2,1,1,1.00,2,2,2,NaN,2,1,3,2,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,100000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,4,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,141.00,1.00,1.00,NaN,NaN,1.00,NaN,1.00,NaN,2.00,2.00,2.00,2.00,48.00,7.00,NaN,2.00,2.00,2.00,2.00,1.00,2.00,720000.00,2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,100000.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,60.00,NaN,NaN,60.00,NaN,NaN,2.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,1.00,18.00,7.00,NaN,8.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2.00,1.00,2.00,1.00,1.00,3.00,NaN,3.00,3.00,NaN,1.00,820000.00,1.00,141.00,9212.00,Cría de ganado bovino y bufalino,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
409122,8473907,1,1,1,1,2,61,6.00,1964.00,1,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,3.00,2.00,NaN,1,1.00,5.00,NaN,4,4,3,4,4,4,4,4,1.00,2.00,NaN,3.00,3.00,NaN,NaN,NaN,1.00,2.00,1.00,20251252,12,2025,1,1,NaN,2,378.31,73,1,1,4,1,2.00,2,2,2,NaN,1,1,4,1,2,1.00,4,1,1,4.00,4,NaN,NaN,NaN,600000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,1,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,9700.00,1.00,1.00,NaN,NaN,1.00,NaN,2.00,NaN,2.00,2.00,2.00,2.00,1.00,3.00,NaN,2.00,2.00,2.00,2.00,1.00,2.00,800000.00,2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,600000.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,48.00,NaN,NaN,48.00,NaN,NaN,1.00,1.00,NaN,3.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,72.00,0.00,4.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,14.00,NaN,NaN,3.00,NaN,1.00,1400000.00,97.00,9700.00,9111.00,Actividades de los hogares individuales como e...,NaN,NaN
409123,8473908,1,1,1,1,1,58,3.00,1967.00,1,3,NaN,3,NaN,2,2.00,2,6,NaN,NaN,3.00,1.00,2.00,1,2.00,1.00,120000.00,4,4,4,4,4,4,4,4,1.00,1.00,2.00,13.00,9.00,111.00,9.00,111.00,2.00,1.00,1.00,20251252,12,2025,1,1,54.00,1,534.55,54,2,1,4,1,2.00,1,1,1,3.00,1,1,4,3,1,1.00,1,1,1,3.00,1,NaN,NaN,300000000.00,700000.00,NaN,NaN,1.00,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,1.00,4,NaN,1.00,6.00,VACACIONES,NaN,2.00,1.00,3.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,8530.00,1.00,2.00,1.00,NaN,2.00,4.00,1.00,8413.00,1.00,1.00,1.00,1.00,60.00,2.00,NaN,2.00,1.00,2.00,1.00,5.00,2.00,3000000.00,2.00,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,1.00,1500000.00,1.00,3000000.00,1.00,1500000.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,30.00,2.00,NaN,0.00,3.00,NaN,10.00,7.00,NaN,1.00,NaN,1.00,3.00,1.00,20.00,1.00,1.00,1.00,0.00,48.00,4.00,NaN,8.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,8.00,NaN,30.00,2.00,NaN,1.00,3000000.00,85.00,8530.00,2330.00,Establecimientos que combinan diferentes nivel...,NaN,NaN
409124,8473908,1,2,1,2,2,51,3.00,1974.00,2,2,NaN,2,NaN,2,1.00,2,6,NaN,NaN,3.00,1.00,1.00,1,1.00,1.00,318240.00,4,4,4,4,4,4,4,4,1.00,2.00,NaN,12.00,4.00,413.00,9.00,413.00,1.00,2.00,1.00,20251252,12,2025,1,1,54.00,1,534.55,54,2,1,4,1,2.00,1,1,1,3.00,1,1,4,3,1,1.00,1,1,1,3.00,1,NaN,NaN,300000000.00,700000.00,NaN,NaN,1.00,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,1.00,4,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,8412.00,1.00,2.00,2.00,24.00,1.00,NaN,1.00,NaN,1.00,1.00,1.00,1.00,23.00,2.00,NaN,2.00,1.00,2.00,1.00,1.00,2.00,7956000.00,1.00,79600.00,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,1.00,3500000.00,1.00,7956000.00,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,44.00,NaN,NaN,44.00,NaN,NaN,10.00,7.00,NaN,1.00,NaN,1.00,2.00,1.00,10.00,1.00,1.00,1.00,4.00,48.00,4.00,NaN,1.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,2.00,NaN,60.00,2.00,NaN,1.00,7956000.00,84.00,8412.00,2411.00,Actividades ejecutivas de la administración pú...,NaN,NaN
409125,8473908,1,3,1,3,2,31,2.00,1994.00,3,1,2.00,1,1.00,2,2.00,2,6,NaN,NaN,6.00,NaN,NaN,1,1.00,3.00,178000.00,4,4,4,4,4,4,4,4,1.00,2.00,NaN,10.00,10.00,719.00,7.00,719.00,1.00,2.00,1.00,20251252,12,2025,1,1,54.00,1,534.55,54,2,1,4,1,2.00,1,1,1,3.00,1,1,4,3,1,1.00,1,1,1,3.00,1,NaN,NaN,300000000.00,700000.00,NaN,NaN,1.00,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,1.00,4,NaN,1.00,2.00,NaN,NaN,2.00,2.00,NaN,NaN,NaN,2.00,1.00,NaN,1.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
409126,8473908,1,4,1,4,2,26,2.00,1999.00,3,1,2.00,1,1.00,2,2.00,2,6,NaN,NaN,6.00,NaN,NaN,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,10.00,10.00,421.00,7.00,421.00,1.00,2.00,1.00,20251252,12,2025,1,1,54.00,1,534.55,54,2,1,4,1,2.00,1,1,1,3.00,1,1,4,3,1,1.00,1,1,1,3.00,1,NaN,NaN,300000000.00,700000.00,NaN,NaN,1.00,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,1.00,4,NaN,1.00,6.00,DESCANSANDO EN SU HOGAR,NaN,2.00,1.00,5.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,4791.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.00,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,3.00,1.00,1.00,1.00,6.00,NaN,NaN,700000.00,1.00,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,500000.00,1.00,NaN,1.00,NaN,1.00,2.00,10.00,10.00,1.00,NaN,0.00,5.00,NaN,1.00,1.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,0.00,6.00,4.00,NaN,3.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,44.00,2.00,2.00,1.00,1.00,1.00,1.00,1.00,2.00,2.00,2.00,2.00,2.00,NaN,1.00,1.00,1.00,2.00,1.00,2.00,2.00,1.00,14.00,NaN,NaN,2.00,NaN,1.00,500000.00,47.00,4791.00,5221.00,Comercio al por menor realizado a través de in...,NaN,NaN

In [140]:
geih_2025.shape

(409127, 315)

Punto 9

In [141]:
nombre_archivo_final = "GEIH_2025_Completa.csv"

geih_2025.to_csv(ruta + nombre_archivo_final, index=False, encoding='utf-8-sig')

print(f"¡Éxito! La base ha sido guardada en: {ruta + nombre_archivo_final}")

¡Éxito! La base ha sido guardada en: /content/drive/MyDrive/GEIH 2025/GEIH_2025_Completa.csv